"""Hook event catalog (harness.md 106)."""

from __future__ import annotations

EVENT_SESSION_START = "SessionStart"
EVENT_BEFORE_MODEL = "BeforeModel"
EVENT_AFTER_MODEL = "AfterModel"
EVENT_PRE_TOOL_USE = "PreToolUse"
EVENT_POST_TOOL_USE = "PostToolUse"
EVENT_TOOL_ERROR = "ToolError"
EVENT_PERMISSION_REQUEST = "PermissionRequest"
EVENT_SUBAGENT_START = "SubagentStart"
EVENT_SUBAGENT_STOP = "SubagentStop"
EVENT_BEFORE_COMPACT = "BeforeCompact"
EVENT_AFTER_COMPACT = "AfterCompact"
EVENT_BEFORE_FINAL = "BeforeFinal"
EVENT_SESSION_END = "SessionEnd"

ALL_EVENTS = (
    EVENT_SESSION_START,
    EVENT_BEFORE_MODEL,
    EVENT_AFTER_MODEL,
    EVENT_PRE_TOOL_USE,
    EVENT_POST_TOOL_USE,
    EVENT_TOOL_ERROR,
    EVENT_PERMISSION_REQUEST,
    EVENT_SUBAGENT_START,
    EVENT_SUBAGENT_STOP,
    EVENT_BEFORE_COMPACT,
    EVENT_AFTER_COMPACT,
    EVENT_BEFORE_FINAL,
    EVENT_SESSION_END,
)

HANDLER_TYPES = ("python", "shell")

__all__ = [
    "ALL_EVENTS",
    "EVENT_AFTER_COMPACT",
    "EVENT_AFTER_MODEL",
    "EVENT_BEFORE_COMPACT",
    "EVENT_BEFORE_FINAL",
    "EVENT_BEFORE_MODEL",
    "EVENT_PERMISSION_REQUEST",
    "EVENT_POST_TOOL_USE",
    "EVENT_PRE_TOOL_USE",
    "EVENT_SESSION_END",
    "EVENT_SESSION_START",
    "EVENT_SUBAGENT_START",
    "EVENT_SUBAGENT_STOP",
    "EVENT_TOOL_ERROR",
    "HANDLER_TYPES",
]
