"""Project / session flow projection (`flow.get`, capability `project_flow_v1`).

A flow tells how a project (or a lone chat) advanced and how the agent took
part: stages ordered in time, their status, progress, executors, files and an
anchor to the turn that opened each one. Everything is **derived from
persisted facts** (turn events, changesets, the task graph, validation
records, checkpoints); nothing is estimated or generated by a model. What is
not known is `None`, and the desktop shows it as "sin datos".

Stage rule: a stage is a contiguous run of turns in the same mode across all
sessions of the scope, ordered by start time. A finished PLAN opens a cycle;
BUILD/REVIEW stages that follow belong to it until the next PLAN.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

MAX_STAGE_FILES = 8
MAX_EXCERPT_CHARS = 160
TERMINAL = {"completed", "failed", "cancelled", "stopped"}
STAGE_KIND_BY_MODE = {"plan": "planning", "review": "review"}
DEFAULT_STAGE_KIND = "implementation"
OPEN_TASK_STATES = {"pending", "in_progress", "blocked"}


@dataclass(slots=True)
class TurnFacts:
    """The few facts about one turn that a flow needs."""

    turn_id: str
    session_id: str
    session_title: str
    mode: str | None
    status: str = "running"
    started_at: str = ""
    completed_at: str | None = None
    user_message: str = ""
    plan_heading: str | None = None
    models: Counter = field(default_factory=Counter)
    agents: Counter = field(default_factory=Counter)
    files: list[dict[str, Any]] = field(default_factory=list)
    verification_passed: int = 0
    verification_failed: int = 0
    pending_interventions: int = 0
    origin_peer: bool = False

    @property
    def stage_kind(self) -> str:
        return STAGE_KIND_BY_MODE.get((self.mode or "").lower(), DEFAULT_STAGE_KIND)


def turn_facts_from_events(record: Any, events: list[Any]) -> list[TurnFacts]:
    """Fold a session's persisted events into per-turn facts, in turn order.

    Reads only what a flow needs: mode and outcome, the user message, the plan
    heading of a finished PLAN, executor models (`model.started`), subagents,
    changeset files, verification outcomes, unresolved approvals/questions
    and peer provenance. Events without `turn_id` (session-level) are ignored.
    """
    by_turn: dict[str, TurnFacts] = {}
    order: list[str] = []
    pending: dict[str, set[str]] = {}
    title = getattr(record, "title", None) or getattr(record, "id", "")
    for row in events:
        turn_id = getattr(row, "turn_id", None)
        if not turn_id:
            continue
        turn_id = str(turn_id)
        facts = by_turn.get(turn_id)
        if facts is None:
            facts = TurnFacts(
                turn_id=turn_id,
                session_id=str(record.id),
                session_title=str(title),
                mode=None,
                started_at=row.created_at,
            )
            by_turn[turn_id] = facts
            order.append(turn_id)
            pending[turn_id] = set()
        payload = dict(row.payload or {})
        name = row.type
        if name == "turn.started":
            facts.mode = payload.get("mode") if isinstance(payload.get("mode"), str) else None
            facts.started_at = str(payload.get("occurred_at") or row.created_at)
            facts.user_message = str(payload.get("message") or "")
            origin = payload.get("origin")
            facts.origin_peer = isinstance(origin, dict) and origin.get("kind") == "peer"
        elif name in {"turn.completed", "turn.failed", "turn.cancelled", "turn.stopped"}:
            facts.status = name.removeprefix("turn.")
            facts.completed_at = str(payload.get("occurred_at") or row.created_at)
        elif name == "model.started":
            model = payload.get("model")
            if isinstance(model, str) and model:
                facts.models[model] += 1
        elif name == "model.content.completed":
            if payload.get("output_kind") == "final" and (facts.mode or "").lower() == "plan":
                facts.plan_heading = plan_heading(str(payload.get("content") or ""))
        elif name == "agent.started":
            agent = payload.get("agent")
            if isinstance(agent, str) and agent:
                facts.agents[agent] += 1
        elif name == "turn.changes.completed":
            for item in payload.get("files") or []:
                if isinstance(item, dict) and isinstance(item.get("path"), str):
                    facts.files.append(
                        {"path": item["path"], "kind": str(item.get("kind") or "modified")}
                    )
        elif name == "verification.completed":
            outcome = str(payload.get("outcome") or "")
            if outcome == "done":
                facts.verification_passed += 1
            elif outcome in {"failed", "partial", "blocked"}:
                facts.verification_failed += 1
        elif name in {"approval.requested", "question.requested"}:
            key = payload.get("approval_id") or payload.get("request_id") or payload.get("id")
            if key:
                pending[turn_id].add(f"{name}:{key}")
        elif name in {
            "approval.resolved",
            "approval.expired",
            "question.resolved",
            "question.expired",
        }:
            key = payload.get("approval_id") or payload.get("request_id") or payload.get("id")
            prefix = "approval.requested" if name.startswith("approval") else "question.requested"
            if key:
                pending[turn_id].discard(f"{prefix}:{key}")
    result: list[TurnFacts] = []
    for turn_id in order:
        facts = by_turn[turn_id]
        # A terminal turn cannot be waiting on anyone, whatever the events say.
        facts.pending_interventions = 0 if facts.status in TERMINAL else len(pending[turn_id])
        result.append(facts)
    return result


_HEADING = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$", re.M)


def plan_heading(content: str) -> str | None:
    """First Markdown heading of a plan, or its first non-empty line."""
    match = _HEADING.search(content)
    if match:
        return excerpt(match.group(1))
    for line in content.splitlines():
        if line.strip():
            return excerpt(line)
    return None


def excerpt(text: str, limit: int = MAX_EXCERPT_CHARS) -> str:
    """Plain-text excerpt: no code fences, no Markdown markers, one line."""
    plain = re.sub(r"```[\s\S]*?```", " ", text)
    plain = re.sub(r"^\s*(?:[-*+]|\d+[.)])\s+", "", plain, flags=re.M)  # list markers
    plain = re.sub(r"[#*_>`~\[\]]", "", plain)
    plain = re.sub(r"\s+", " ", plain).strip()
    if len(plain) <= limit:
        return plain
    return plain[: limit - 1].rstrip() + "…"


@dataclass(slots=True)
class Stage:
    index: int
    cycle_index: int
    kind: str
    turns: list[TurnFacts]

    @property
    def started_at(self) -> str:
        return self.turns[0].started_at

    @property
    def last(self) -> TurnFacts:
        return self.turns[-1]

    @property
    def completed_at(self) -> str | None:
        if any(turn.status not in TERMINAL for turn in self.turns):
            return None
        return max((turn.completed_at or "" for turn in self.turns), default=None) or None


def group_stages(turns: list[TurnFacts]) -> list[Stage]:
    ordered = sorted(turns, key=lambda turn: (turn.started_at, turn.turn_id))
    stages: list[Stage] = []
    cycle = 0
    for turn in ordered:
        kind = turn.stage_kind
        if stages and stages[-1].kind == kind:
            stages[-1].turns.append(turn)
            continue
        if kind == "planning" or cycle == 0:
            cycle += 1
        stages.append(Stage(index=len(stages) + 1, cycle_index=cycle, kind=kind, turns=[turn]))
    return stages


def stage_status(stage: Stage) -> str:
    running = [turn for turn in stage.turns if turn.status not in TERMINAL]
    if running:
        return "needs_you" if any(turn.pending_interventions for turn in running) else "active"
    last = stage.last.status
    if last == "completed":
        return "done"
    if last == "failed":
        return "failed"
    return "stopped"


def _within(value: str | None, start: str, end: str | None) -> bool:
    if not value:
        return False
    return value >= start and (end is None or value <= end)


def stage_progress(stage: Stage, status: str, tasks: list[dict[str, Any]] | None) -> float | None:
    """Honest progress: task graph for BUILD, plan completion for PLAN,
    verification outcomes for REVIEW. Without evidence it is ``None``, never a
    ratio of turns on an unfinished stage."""
    if stage.kind == "planning":
        return 1.0 if status == "done" else None
    if stage.kind == "review":
        passed = sum(turn.verification_passed for turn in stage.turns)
        failed = sum(turn.verification_failed for turn in stage.turns)
        return passed / (passed + failed) if passed + failed else None
    if tasks:
        end = stage.completed_at
        touched = [
            task
            for task in tasks
            if _within(task.get("created_at"), stage.started_at, end)
            or _within(task.get("updated_at"), stage.started_at, end)
        ]
        if touched:
            done = sum(1 for task in touched if task.get("status") == "done")
            return done / len(touched)
    return 1.0 if status == "done" else None


def _timestamp_ms(value: str | None) -> float | None:
    if not value:
        return None
    from datetime import datetime

    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp() * 1000
    except ValueError:
        return None


def stage_payload(
    stage: Stage, tasks: list[dict[str, Any]] | None, checkpoints: list[dict]
) -> dict:
    status = stage_status(stage)
    first = stage.turns[0]
    heading = next((turn.plan_heading for turn in stage.turns if turn.plan_heading), None)
    title = heading if stage.kind == "planning" and heading else excerpt(first.user_message)
    models: Counter = Counter()
    agents: Counter = Counter()
    sessions: dict[str, dict[str, Any]] = {}
    files: dict[str, dict[str, Any]] = {}
    passed = failed = peer = 0
    for turn in stage.turns:
        models.update(turn.models)
        agents.update(turn.agents)
        entry = sessions.setdefault(
            turn.session_id,
            {"session_id": turn.session_id, "title": turn.session_title, "turns": 0},
        )
        entry["turns"] += 1
        for item in turn.files:
            files[item["path"]] = {**item, "turn_id": turn.turn_id}
        passed += turn.verification_passed
        failed += turn.verification_failed
        peer += 1 if turn.origin_peer else 0
    started = _timestamp_ms(stage.started_at)
    completed = _timestamp_ms(stage.completed_at)
    duration = int(completed - started) if started is not None and completed is not None else None
    end = stage.completed_at
    stage_checkpoints = sum(
        1 for row in checkpoints if _within(str(row.get("created_at") or ""), stage.started_at, end)
    )
    ordered_files = list(files.values())
    return {
        "id": f"stg_{first.turn_id}",
        "index": stage.index,
        "cycle_index": stage.cycle_index,
        "kind": stage.kind,
        "mode": first.mode,
        "title": title or "",
        "excerpt": excerpt(first.user_message),
        "status": status,
        "started_at": stage.started_at,
        "completed_at": stage.completed_at,
        "duration_ms": duration if duration is None or duration >= 0 else None,
        "progress": stage_progress(stage, status, tasks),
        "turns": len(stage.turns),
        "executors": [{"model": model, "calls": calls} for model, calls in models.most_common()],
        "agents": [{"agent": agent, "runs": runs} for agent, runs in agents.most_common()],
        "sessions": list(sessions.values()),
        "files": ordered_files[:MAX_STAGE_FILES],
        "files_more": max(0, len(ordered_files) - MAX_STAGE_FILES),
        "verification": {"passed": passed, "failed": failed} if passed + failed else None,
        "checkpoints": stage_checkpoints,
        "origin_peer_turns": peer,
        "anchor": {"session_id": first.session_id, "turn_id": first.turn_id},
    }


def build_flow(
    *,
    scope: dict[str, Any],
    turns: list[TurnFacts],
    tasks: list[dict[str, Any]] | None,
    checkpoints: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    stages = group_stages(turns)
    payloads = [stage_payload(stage, tasks, checkpoints or []) for stage in stages]
    all_files = {item["path"] for stage in stages for turn in stage.turns for item in turn.files}
    weighted = [
        (payload["progress"], payload["turns"])
        for payload in payloads
        if payload["progress"] is not None
    ]
    total_weight = sum(weight for _, weight in weighted)
    progress = (
        sum(value * weight for value, weight in weighted) / total_weight if total_weight else None
    )
    ordered = sorted(turns, key=lambda turn: (turn.started_at, turn.turn_id))
    last_activity = max((turn.completed_at or turn.started_at for turn in ordered), default=None)
    return {
        "scope": scope,
        "summary": {
            "stages_total": len(payloads),
            "stages_done": sum(1 for payload in payloads if payload["status"] == "done"),
            "stages_active": sum(
                1 for payload in payloads if payload["status"] in {"active", "needs_you"}
            ),
            "turns_total": len(turns),
            "turns_failed": sum(1 for turn in turns if turn.status == "failed"),
            "files_changed": len(all_files),
            "tasks": (
                {
                    "total": len(tasks),
                    "done": sum(1 for task in tasks if task.get("status") == "done"),
                    "open": sum(1 for task in tasks if task.get("status") in OPEN_TASK_STATES),
                }
                if tasks is not None
                else None
            ),
            "progress": progress,
            "started_at": ordered[0].started_at if ordered else None,
            "last_activity_at": last_activity,
        },
        "stages": payloads,
    }


def collect_flow(
    services: Any, *, project_id: str | None = None, session_id: str | None = None
) -> dict[str, Any]:
    """Gather the persisted facts of a scope and project its flow.

    Exactly one of ``project_id`` / ``session_id`` must be given (the caller
    validates its own parameter contract). A project scope covers every
    session that references the project by id or, for sessions created before
    the project was registered, by root snapshot. A moved or deleted folder
    degrades to "no task data" instead of failing.
    """
    from pathlib import Path

    from rinari.shared.errors import InvalidUsageError, RinariError

    if bool(project_id) == bool(session_id):
        raise InvalidUsageError("Provide exactly one of project_id or session_id.")
    root: str | None
    if session_id:
        record = services.sessions.show(session_id)
        sessions = [record]
        root = record.project_root_snapshot if record.kind == "PROJECT" else None
        scope = {
            "kind": "session",
            "id": record.id,
            "title": record.title or record.id,
            "root": root,
        }
    else:
        project = services.projects.get(str(project_id))
        root = project.canonical_root
        sessions = [
            row
            for row in services.sessions.list(limit=500)
            if row.project_id == project.id or row.project_root_snapshot == root
        ]
        scope = {
            "kind": "project",
            "id": project.id,
            "title": project.name or Path(root).name or root,
            "root": root,
        }
    turns: list[TurnFacts] = []
    for row in sessions:
        turns.extend(turn_facts_from_events(row, services.ctx.event_repo.list(row.id)))
    tasks: list[dict[str, Any]] | None = None
    checkpoints: list[dict[str, Any]] = []
    if root:
        try:
            tasks = list(services.tasks.tree(root)["tasks"])
        except RinariError:
            tasks = None
        try:
            checkpoints = list(services.checkpoints.list(root))
        except RinariError:
            checkpoints = []
    return build_flow(scope=scope, turns=turns, tasks=tasks, checkpoints=checkpoints)


__all__ = [
    "MAX_STAGE_FILES",
    "TurnFacts",
    "build_flow",
    "collect_flow",
    "excerpt",
    "group_stages",
    "plan_heading",
    "stage_progress",
    "stage_status",
    "turn_facts_from_events",
]
