"""Project / session flow projection (`flow.get`, capability `project_flow_v1`).

A flow tells how a project (or a lone chat) advanced and how the agent took
part: stages ordered in time, their status, progress, executors, files and an
anchor to the turn that opened each one. Everything is **derived from
persisted facts** (turn events, changesets, the task graph, validation
records, checkpoints); nothing is estimated or generated by a model. What is
not known is `None`, and the desktop shows it as "sin datos".

Stage rule: a stage is a contiguous run of turns in the same mode across all
sessions of the scope, ordered by start time. A finished PLAN opens a cycle;
BUILD/REVIEW stages that follow belong to it until the next PLAN.
"""

from __future__ import annotations

import hashlib
import re
from collections import Counter, OrderedDict
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

MAX_STAGE_FILES = 8
MAX_EXCERPT_CHARS = 160
#: Cota contractual de etapas por respuesta.
#:
#: Un flujo no puede crecer sin límite: `NdjsonTransport` corta a 16 MiB y una
#: línea que lo supere no devuelve un error, derriba el stream entero. Se
#: entregan las más **recientes**, que es lo que se mira, y la respuesta dice
#: cuántas quedaron fuera y por dónde seguir.
MAX_STAGES = 200
#: Topes de las listas que acompañan a cada etapa. El schema también los
#: declara, pero el schema valida lo que ya se construyó: si la cota no está
#: además en runtime, la respuesta grande se arma igual antes de rechazarse.
MAX_STAGE_SESSIONS = 32
MAX_STAGE_EXECUTORS = 16
MAX_STAGE_AGENTS = 16
TERMINAL = {"completed", "failed", "cancelled", "stopped"}
STAGE_KIND_BY_MODE = {"plan": "planning", "review": "review"}
DEFAULT_STAGE_KIND = "implementation"
#: Modo de un turno que no lo declara o lo declara vacío. Explícito a
#: propósito: mezclarlo con el modo anterior fundiría en una sola etapa dos
#: corridas que el usuario vivió por separado.
UNKNOWN_MODE = "unknown"
OPEN_TASK_STATES = {"pending", "in_progress", "blocked"}
#: Los únicos eventos que esta proyección mira.
#:
#: Cargar el historial entero para quedarse con esto hacía que el coste
#: creciera con toda la conversación —los deltas del modelo son la mayoría de
#: las filas y no aportan nada aquí—.
FLOW_EVENT_TYPES = (
    "turn.started",
    "turn.completed",
    "turn.failed",
    "turn.cancelled",
    "turn.stopped",
    "model.started",
    "model.content.completed",
    "agent.started",
    "turn.changes.completed",
    "verification.completed",
    "approval.requested",
    "approval.resolved",
    "approval.expired",
    "question.requested",
    "question.resolved",
    "question.expired",
)


def normalized_mode(mode: str | None) -> str:
    """El modo con el que se compara. Nunca `None`, nunca vacío."""
    value = (mode or "").strip().lower()
    return value or UNKNOWN_MODE


@dataclass(slots=True)
class TurnFacts:
    """The few facts about one turn that a flow needs."""

    turn_id: str
    session_id: str
    session_title: str
    mode: str | None
    status: str = "running"
    started_at: str = ""
    completed_at: str | None = None
    user_message: str = ""
    plan_heading: str | None = None
    models: Counter = field(default_factory=Counter)
    agents: Counter = field(default_factory=Counter)
    files: list[dict[str, Any]] = field(default_factory=list)
    verification_passed: int = 0
    verification_failed: int = 0
    pending_interventions: int = 0
    origin_peer: bool = False

    @property
    def normalized_mode(self) -> str:
        return normalized_mode(self.mode)

    @property
    def stage_kind(self) -> str:
        """PLAN / BUILD / REVIEW, que es **presentación**.

        No es lo que separa etapas: `ask`, `agent` y `full-access` comparten
        `implementation` y son modos distintos. La frontera la pone el modo.
        """
        return STAGE_KIND_BY_MODE.get(self.normalized_mode, DEFAULT_STAGE_KIND)


def turn_facts_from_events(record: Any, events: list[Any]) -> list[TurnFacts]:
    """Fold a session's persisted events into per-turn facts, in turn order.

    Reads only what a flow needs: mode and outcome, the user message, the plan
    heading of a finished PLAN, executor models (`model.started`), subagents,
    changeset files, verification outcomes, unresolved approvals/questions
    and peer provenance. Events without `turn_id` (session-level) are ignored.
    """
    by_turn: dict[str, TurnFacts] = {}
    order: list[str] = []
    pending: dict[str, set[str]] = {}
    title = getattr(record, "title", None) or getattr(record, "id", "")
    for row in events:
        turn_id = getattr(row, "turn_id", None)
        if not turn_id:
            continue
        turn_id = str(turn_id)
        facts = by_turn.get(turn_id)
        if facts is None:
            facts = TurnFacts(
                turn_id=turn_id,
                session_id=str(record.id),
                session_title=str(title),
                mode=None,
                started_at=row.created_at,
            )
            by_turn[turn_id] = facts
            order.append(turn_id)
            pending[turn_id] = set()
        payload = dict(row.payload or {})
        name = row.type
        if name == "turn.started":
            facts.mode = payload.get("mode") if isinstance(payload.get("mode"), str) else None
            facts.started_at = str(payload.get("occurred_at") or row.created_at)
            facts.user_message = str(payload.get("message") or "")
            origin = payload.get("origin")
            facts.origin_peer = isinstance(origin, dict) and origin.get("kind") == "peer"
        elif name in {"turn.completed", "turn.failed", "turn.cancelled", "turn.stopped"}:
            facts.status = name.removeprefix("turn.")
            facts.completed_at = str(payload.get("occurred_at") or row.created_at)
        elif name == "model.started":
            model = payload.get("model")
            if isinstance(model, str) and model:
                facts.models[model] += 1
        elif name == "model.content.completed":
            if payload.get("output_kind") == "final" and (facts.mode or "").lower() == "plan":
                facts.plan_heading = plan_heading(str(payload.get("content") or ""))
        elif name == "agent.started":
            agent = payload.get("agent")
            if isinstance(agent, str) and agent:
                facts.agents[agent] += 1
        elif name == "turn.changes.completed":
            for item in payload.get("files") or []:
                if isinstance(item, dict) and isinstance(item.get("path"), str):
                    facts.files.append(
                        {"path": item["path"], "kind": str(item.get("kind") or "modified")}
                    )
        elif name == "verification.completed":
            outcome = str(payload.get("outcome") or "")
            if outcome == "done":
                facts.verification_passed += 1
            elif outcome in {"failed", "partial", "blocked"}:
                facts.verification_failed += 1
        elif name in {"approval.requested", "question.requested"}:
            key = payload.get("approval_id") or payload.get("request_id") or payload.get("id")
            if key:
                pending[turn_id].add(f"{name}:{key}")
        elif name in {
            "approval.resolved",
            "approval.expired",
            "question.resolved",
            "question.expired",
        }:
            key = payload.get("approval_id") or payload.get("request_id") or payload.get("id")
            prefix = "approval.requested" if name.startswith("approval") else "question.requested"
            if key:
                pending[turn_id].discard(f"{prefix}:{key}")
    result: list[TurnFacts] = []
    for turn_id in order:
        facts = by_turn[turn_id]
        # A terminal turn cannot be waiting on anyone, whatever the events say.
        facts.pending_interventions = 0 if facts.status in TERMINAL else len(pending[turn_id])
        result.append(facts)
    return result


_HEADING = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$", re.M)


def plan_heading(content: str) -> str | None:
    """First Markdown heading of a plan, or its first non-empty line."""
    match = _HEADING.search(content)
    if match:
        return excerpt(match.group(1))
    for line in content.splitlines():
        if line.strip():
            return excerpt(line)
    return None


def excerpt(text: str, limit: int = MAX_EXCERPT_CHARS) -> str:
    """Plain-text excerpt: no code fences, no Markdown markers, one line."""
    plain = re.sub(r"```[\s\S]*?```", " ", text)
    plain = re.sub(r"^\s*(?:[-*+]|\d+[.)])\s+", "", plain, flags=re.M)  # list markers
    plain = re.sub(r"[#*_>`~\[\]]", "", plain)
    plain = re.sub(r"\s+", " ", plain).strip()
    if len(plain) <= limit:
        return plain
    return plain[: limit - 1].rstrip() + "…"


@dataclass(slots=True)
class Stage:
    index: int
    cycle_index: int
    kind: str
    #: El único modo de esta etapa. Todos sus turnos lo comparten, porque es
    #: justo lo que la delimita.
    mode: str
    turns: list[TurnFacts]

    @property
    def started_at(self) -> str:
        return self.turns[0].started_at

    @property
    def last(self) -> TurnFacts:
        return self.turns[-1]

    @property
    def completed_at(self) -> str | None:
        if any(turn.status not in TERMINAL for turn in self.turns):
            return None
        return max((turn.completed_at or "" for turn in self.turns), default=None) or None


def group_stages(turns: list[TurnFacts]) -> list[Stage]:
    """Etapas: corridas contiguas de turnos **del mismo modo**.

    Antes se agrupaba por `kind`, y como `ask`, `agent`, `full-access` y lo
    desconocido comparten `implementation`, tres turnos de modos distintos
    caían en la misma etapa — y el payload se quedaba con el modo del primero,
    así que decía de esa etapa algo que sólo valía para un turno.

    Un ciclo se abre al **empezar** un PLAN, no al terminarlo: así el ciclo en
    curso se puede enseñar mientras se planifica.
    """
    ordered = sorted(turns, key=_order_key)
    stages: list[Stage] = []
    cycle = 0
    for turn in ordered:
        mode = turn.normalized_mode
        if stages and stages[-1].mode == mode:
            stages[-1].turns.append(turn)
            continue
        kind = turn.stage_kind
        if kind == "planning" or cycle == 0:
            cycle += 1
        stages.append(
            Stage(index=len(stages) + 1, cycle_index=cycle, kind=kind, mode=mode, turns=[turn])
        )
    return stages


def stage_status(stage: Stage) -> str:
    running = [turn for turn in stage.turns if turn.status not in TERMINAL]
    if running:
        return "needs_you" if any(turn.pending_interventions for turn in running) else "active"
    last = stage.last.status
    if last == "completed":
        return "done"
    if last == "failed":
        return "failed"
    return "stopped"


def _instant(value: str | None) -> datetime | None:
    """ISO-8601 a UTC, o ``None`` si no se puede leer.

    Comparar estas marcas como cadenas es incorrecto: `Z` y `+00:00` son el
    mismo instante y ordenan distinto, y dos offsets equivalentes con
    fracciones distintas también. Una fecha ilegible es un hecho desconocido,
    no una que sea "menor que" las demás.
    """
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)


def _within(value: str | None, start: str, end: str | None) -> bool:
    """¿Cae ``value`` dentro de la ventana? Una fecha ilegible no cuenta."""
    moment = _instant(value)
    begin = _instant(start)
    if moment is None or begin is None:
        return False
    if moment < begin:
        return False
    finish = _instant(end) if end else None
    return finish is None or moment <= finish


def _order_key(turn: TurnFacts) -> tuple[datetime, str]:
    """Orden estable de turnos: instante y, a igualdad, `turn_id`.

    Un turno sin fecha legible va al final en vez de colarse al principio por
    comparación lexicográfica.
    """
    moment = _instant(turn.started_at)
    return (moment or datetime.max.replace(tzinfo=UTC), turn.turn_id)


def stage_task_snapshot(
    stage: Stage, tasks: list[dict[str, Any]] | None
) -> dict[str, int] | None:
    """Tareas del grafo **de ahora** cuya ventana toca esta etapa.

    Es una foto del presente, no el estado que tenían cuando la etapa corría.
    La pertenencia se decide por `created_at`/`updated_at` pero el estado sale
    del grafo actual, así que una tarea creada aquí y terminada mucho después
    aparecería como progreso retroactivo de una etapa ya cerrada. Por eso se
    llama snapshot y sólo alimenta el progreso de una etapa **viva**, donde
    «ahora» y «entonces» son lo mismo.
    """
    if not tasks:
        return None
    end = stage.completed_at
    touched = [
        task
        for task in tasks
        if _within(task.get("created_at"), stage.started_at, end)
        or _within(task.get("updated_at"), stage.started_at, end)
    ]
    if not touched:
        return None
    return {
        "total": len(touched),
        "done": sum(1 for task in touched if task.get("status") == "done"),
        "open": sum(1 for task in touched if task.get("status") in OPEN_TASK_STATES),
    }


def stage_progress(
    stage: Stage,
    status: str,
    snapshot: dict[str, int] | None,
) -> float | None:
    """Progreso honesto, o ``None``.

    - **PLAN**: terminado es 1.0; mientras corre no se sabe.
    - **REVIEW**: proporción de verificaciones **aprobadas** sobre las
      ejecutadas. No es porcentaje temporal de avance: una etapa con una de
      dos verificaciones aprobadas da 0.5 aunque haya terminado.
    - **BUILD**: proporción de tareas hechas, y sólo mientras la etapa está
      viva. Una etapa de build terminada **sin** evidencia de tareas devuelve
      `None`, no 1.0: que un turno acabe no dice cuánto del trabajo se hizo, y
      afirmarlo era comunicar una certeza que no existe.
    """
    if stage.kind == "planning":
        return 1.0 if status == "done" else None
    if stage.kind == "review":
        passed = sum(turn.verification_passed for turn in stage.turns)
        failed = sum(turn.verification_failed for turn in stage.turns)
        return passed / (passed + failed) if passed + failed else None
    # Sólo la etapa viva puede usar el grafo actual como su propio estado.
    if snapshot and status in {"active", "needs_you"}:
        return snapshot["done"] / snapshot["total"]
    return None


def _timestamp_ms(value: str | None) -> float | None:
    moment = _instant(value)
    return moment.timestamp() * 1000 if moment is not None else None


def stage_payload(
    stage: Stage, tasks: list[dict[str, Any]] | None, checkpoints: list[dict]
) -> dict:
    status = stage_status(stage)
    first = stage.turns[0]
    heading = next((turn.plan_heading for turn in stage.turns if turn.plan_heading), None)
    title = heading if stage.kind == "planning" and heading else excerpt(first.user_message)
    models: Counter = Counter()
    agents: Counter = Counter()
    sessions: dict[str, dict[str, Any]] = {}
    files: dict[str, dict[str, Any]] = {}
    passed = failed = peer = 0
    for turn in stage.turns:
        models.update(turn.models)
        agents.update(turn.agents)
        entry = sessions.setdefault(
            turn.session_id,
            {"session_id": turn.session_id, "title": turn.session_title, "turns": 0},
        )
        entry["turns"] += 1
        for item in turn.files:
            files[item["path"]] = {**item, "turn_id": turn.turn_id}
        passed += turn.verification_passed
        failed += turn.verification_failed
        peer += 1 if turn.origin_peer else 0
    started = _timestamp_ms(stage.started_at)
    completed = _timestamp_ms(stage.completed_at)
    duration = int(completed - started) if started is not None and completed is not None else None
    end = stage.completed_at
    stage_checkpoints = sum(
        1 for row in checkpoints if _within(str(row.get("created_at") or ""), stage.started_at, end)
    )
    ordered_files = list(files.values())
    snapshot = stage_task_snapshot(stage, tasks)
    return {
        "id": f"stg_{first.turn_id}",
        "index": stage.index,
        "cycle_index": stage.cycle_index,
        "kind": stage.kind,
        # El modo de la etapa entera: es lo que la delimita, así que todos sus
        # turnos lo comparten.
        "mode": stage.mode,
        "title": title or "",
        "excerpt": excerpt(first.user_message),
        "status": status,
        "started_at": stage.started_at,
        "completed_at": stage.completed_at,
        "duration_ms": duration if duration is None or duration >= 0 else None,
        "progress": stage_progress(stage, status, snapshot),
        # Foto del grafo de tareas de **ahora**, no el estado histórico de la
        # etapa. Se publica con su nombre para que nadie lo lea como avance
        # pasado (ver `stage_task_snapshot`).
        "current_task_snapshot": snapshot,
        "turns": len(stage.turns),
        # Una etapa puede terminar en `done` habiendo tenido fallos por el
        # camino. El estado final no lo cuenta, así que se cuenta aparte.
        "turns_failed": sum(1 for turn in stage.turns if turn.status == "failed"),
        "turns_stopped": sum(
            1 for turn in stage.turns if turn.status in {"stopped", "cancelled"}
        ),
        "executors": [
            {"model": model, "calls": calls}
            for model, calls in models.most_common(MAX_STAGE_EXECUTORS)
        ],
        "agents": [
            {"agent": agent, "runs": runs} for agent, runs in agents.most_common(MAX_STAGE_AGENTS)
        ],
        "sessions": list(sessions.values())[:MAX_STAGE_SESSIONS],
        "sessions_more": max(0, len(sessions) - MAX_STAGE_SESSIONS),
        "files": ordered_files[:MAX_STAGE_FILES],
        "files_more": max(0, len(ordered_files) - MAX_STAGE_FILES),
        "verification": {"passed": passed, "failed": failed} if passed + failed else None,
        "checkpoints": stage_checkpoints,
        "origin_peer_turns": peer,
        "anchor": {"session_id": first.session_id, "turn_id": first.turn_id},
    }


def flow_revision(parts: Iterable[str]) -> str:
    """Huella del alcance: cambia cuando cambia cualquier hecho que lo alimenta.

    Es lo que permite invalidar sin adivinar. El escritorio no puede decidir
    si refrescar mirando si una sesión aparece en las etapas —una sesión
    recién creada todavía no tiene turnos y no aparecería—, así que la
    pertenencia y el estado se resumen aquí: sesiones del alcance, hasta dónde
    llegaron sus eventos, y la forma de tareas y checkpoints.

    Una respuesta con una revisión anterior no debe reemplazar a otra más
    nueva, y dos consultas de la misma revisión describen el mismo flujo.
    """
    payload = "\n".join(sorted(parts)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()[:16]


def build_flow(
    *,
    scope: dict[str, Any],
    turns: list[TurnFacts],
    tasks: list[dict[str, Any]] | None,
    checkpoints: list[dict[str, Any]] | None = None,
    revision: str | None = None,
    before: str | None = None,
) -> dict[str, Any]:
    stages = group_stages(turns)
    payloads = [stage_payload(stage, tasks, checkpoints or []) for stage in stages]
    # El resumen se calcula sobre el flujo **entero**, no sobre la página: los
    # totales de una vista paginada tienen que seguir siendo los de verdad.
    todas = payloads
    # `before` es el id de una etapa, no un índice: los índices se recalculan
    # en cada proyección y un cursor que se mueve no es un cursor.
    if before:
        corte = next((i for i, payload in enumerate(todas) if payload["id"] == before), None)
        payloads = todas[:corte] if corte is not None else todas
    # Se entregan las más recientes: es lo que se mira primero.
    omitidas = max(0, len(payloads) - MAX_STAGES)
    pagina = payloads[-MAX_STAGES:] if omitidas else payloads
    all_files = {item["path"] for stage in stages for turn in stage.turns for item in turn.files}
    # El resumen **no** puede esconder lo que no se sabe.
    #
    # Antes se promediaban sólo las etapas con progreso conocido, así que un
    # PLAN terminado (100 %) junto a un BUILD activo sin evidencia daba un
    # resumen de 100 % mientras el trabajo seguía. El número decía «terminado»
    # de algo que estaba a medias.
    #
    # Ahora, si alguna etapa tiene progreso desconocido el total es `None`, y
    # se publica aparte cuántas etapas se conocen para que la interfaz pueda
    # decir «parcial» sin fingir un total.
    known = [payload for payload in todas if payload["progress"] is not None]
    total_weight = sum(payload["turns"] for payload in known)
    partial = (
        sum(payload["progress"] * payload["turns"] for payload in known) / total_weight
        if total_weight
        else None
    )
    progress = partial if todas and len(known) == len(todas) else None
    ordered = sorted(turns, key=_order_key)
    last_activity = max((turn.completed_at or turn.started_at for turn in ordered), default=None)
    return {
        "scope": scope,
        # Sin revisión explícita se deriva de los turnos, que es lo único que
        # este nivel conoce. `collect_flow` pasa la de verdad, que incluye
        # membresía, tareas y checkpoints.
        "revision": revision
        or flow_revision(
            f"turn:{turn.turn_id}:{turn.status}:{turn.completed_at}" for turn in turns
        ),
        "summary": {
            "stages_total": len(todas),
            "stages_done": sum(1 for payload in todas if payload["status"] == "done"),
            "stages_active": sum(
                1 for payload in todas if payload["status"] in {"active", "needs_you"}
            ),
            "turns_total": len(turns),
            "turns_failed": sum(1 for turn in turns if turn.status == "failed"),
            "files_changed": len(all_files),
            "tasks": (
                {
                    "total": len(tasks),
                    "done": sum(1 for task in tasks if task.get("status") == "done"),
                    "open": sum(1 for task in tasks if task.get("status") in OPEN_TASK_STATES),
                }
                if tasks is not None
                else None
            ),
            "progress": progress,
            # Cobertura del número de arriba: con qué parte del flujo se ha
            # podido calcular. `progress` es `None` en cuanto falta una etapa,
            # y esto dice cuántas faltan.
            "progress_coverage": {
                "known_stages": len(known),
                "total_stages": len(todas),
                # Promedio de lo conocido, **rotulado como parcial**. Nunca se
                # presenta como progreso total.
                "partial_progress": partial,
            },
            "started_at": ordered[0].started_at if ordered else None,
            "last_activity_at": last_activity,
        },
        "stages": pagina,
        # Truncar en silencio es lo que hacía el tope de 500 sesiones. Si
        # falta historial se dice, con cuánto falta y por dónde seguir.
        "truncated": bool(omitidas),
        "stages_omitted": omitidas,
        "next_cursor": pagina[0]["id"] if omitidas and pagina else None,
    }


#: Última proyección por alcance, para no recomputar en una ráfaga.
#:
#: La clave es el alcance y el valor lleva su revisión: si los hechos no se
#: han movido, la respuesta es la misma y no hace falta volver a plegar todos
#: los eventos. Acotada porque es estado de proceso, no una caché de verdad;
#: se queda con los alcances usados hace poco.
_CACHE: OrderedDict[tuple[str, str], tuple[str, dict[str, Any]]] = OrderedDict()
MAX_CACHED_SCOPES = 8


def reset_flow_cache() -> None:
    """Olvida lo proyectado. La usan las pruebas y el reinicio del Engine."""
    _CACHE.clear()


def collect_flow(
    services: Any,
    *,
    project_id: str | None = None,
    session_id: str | None = None,
    before: str | None = None,
) -> dict[str, Any]:
    """Gather the persisted facts of a scope and project its flow.

    Exactly one of ``project_id`` / ``session_id`` must be given (the caller
    validates its own parameter contract). A project scope covers every
    session that references the project by id or, for sessions created before
    the project was registered, by root snapshot. A moved or deleted folder
    degrades to "no task data" instead of failing.
    """
    from pathlib import Path

    from rinari.shared.errors import InvalidUsageError

    if bool(project_id) == bool(session_id):
        raise InvalidUsageError("Provide exactly one of project_id or session_id.")
    root: str | None
    if session_id:
        record = services.sessions.show(session_id)
        sessions = [record]
        root = record.project_root_snapshot if record.kind == "PROJECT" else None
        scope = {
            "kind": "session",
            "id": record.id,
            "title": record.title or record.id,
            "root": root,
        }
    else:
        project = services.projects.get(str(project_id))
        root = project.canonical_root
        # Por consulta y sin tope: antes se pedían las 500 sesiones más
        # recientes de **todo** el Engine y se filtraba en Python, así que un
        # proyecto con sesiones más antiguas que ese corte salía truncado sin
        # que nada lo indicara.
        sessions = services.ctx.session_repo.for_project(project.id, root)
        scope = {
            "kind": "project",
            "id": project.id,
            "title": project.name or Path(root).name or root,
            "root": root,
        }
    turns: list[TurnFacts] = []
    # La revisión se compone mientras se leen los hechos: qué sesiones forman
    # el alcance y hasta dónde llegó cada una. Incluye las sesiones **sin
    # turnos**, que es lo que permite al escritorio enterarse de una sesión
    # recién creada sin esperar a que produzca actividad.
    marcas = [f"scope:{scope['kind']}:{scope['id']}"]
    for row in sessions:
        marcas.append(f"session:{row.id}:{services.ctx.event_repo.last_seq(row.id)}:{row.state}")
        turns.extend(
            turn_facts_from_events(
                row, services.ctx.event_repo.list(row.id, types=FLOW_EVENT_TYPES)
            )
        )
    tasks: list[dict[str, Any]] | None = None
    checkpoints: list[dict[str, Any]] = []
    # La carpeta ausente se comprueba **antes** de preguntar, en vez de
    # capturar la excepción que sale al preguntar. Antes se capturaba
    # cualquier `RinariError` y se devolvía «sin datos», así que una base de
    # datos corrupta, un permiso denegado o un fallo de esquema quedaban
    # indistinguibles de un proyecto que nunca tuvo tareas: un error real
    # disfrazado de hecho. Con la precondición explícita, lo que salga de
    # estas llamadas es un problema de verdad y sube.
    if root and Path(root).is_dir():
        tasks = list(services.tasks.tree(root)["tasks"])
        # Los checkpoints se apoyan en Git, así que un proyecto sin repositorio
        # sencillamente no tiene. Es una función no disponible, no un fallo, y
        # se comprueba igual que la carpeta: preguntando antes. `.git` puede
        # ser un fichero en un worktree, así que basta con que exista.
        if (Path(root) / ".git").exists():
            checkpoints = list(services.checkpoints.list(root))
    # Tareas y checkpoints entran en la revisión: cambiar el estado de una
    # tarea mueve el progreso de una etapa viva, así que tiene que invalidar
    # aunque no haya ocurrido ningún turno.
    for task in tasks or ():
        marcas.append(f"task:{task.get('id')}:{task.get('status')}:{task.get('updated_at')}")
    for row in checkpoints:
        marcas.append(f"checkpoint:{row.get('id')}:{row.get('created_at')}")
    revision = flow_revision(marcas)
    # Misma revisión y misma página: los hechos no se han movido, así que
    # volver a plegar los eventos daría exactamente esto.
    clave = (str(scope["kind"]), str(scope["id"]))
    recordado = _CACHE.get(clave)
    if recordado is not None and recordado[0] == revision and recordado[1].get("_cursor") == before:
        _CACHE.move_to_end(clave)
        return {k: v for k, v in recordado[1].items() if k != "_cursor"}

    flow = build_flow(
        scope=scope,
        turns=turns,
        tasks=tasks,
        checkpoints=checkpoints,
        revision=revision,
        before=before,
    )
    _CACHE[clave] = (revision, {**flow, "_cursor": before})
    _CACHE.move_to_end(clave)
    while len(_CACHE) > MAX_CACHED_SCOPES:
        _CACHE.popitem(last=False)
    return flow


__all__ = [
    "MAX_STAGE_FILES",
    "TurnFacts",
    "build_flow",
    "collect_flow",
    "excerpt",
    "group_stages",
    "plan_heading",
    "stage_progress",
    "stage_status",
    "turn_facts_from_events",
]
